Styling
FACN3/easyRep pull request #34
Opened 2018-02-16 08:38 UTC by MarlenAw

2018-02-16 11:42 UTC, MynahMarie commented
@MarlenAw Hey Marlen, good job on the styling of the home page! Just a few comment...

- The "View Reports" button: it's not clear that this is a button and it's clickable... maybe make it more like a button to encourage users to click on it.
- The text on the other pages dispappears because all the text is white
- I really like the background image for the home page but not sure for the other pages if we should keep it...
- the categories buttons are also on a white background, maybe you can decide on a different color?
- also the "Back" and "Next" buttons are on white background so whatever color u decide for the icons we could maybe use the same one for those buttons as well?
- finally, if you change the orange on the landing then we need to inform tachyons to always use that orange (it's still set as the previous orange on the style.css file

It looks like alot of comments but really its just color issues, once u decide on a color scheme it should be really easy to just apply that everywhere. ❤️

2018-02-16 11:45 UTC, MynahMarie requested changes
- The "View Reports" button: it's not clear that this is a button and it's clickable... maybe make it more like a button to encourage users to click on it.
- The text on the other pages dispappears because all the text is white
- I really like the background image for the home page but not sure for the other pages if we should keep it...
- the categories buttons are also on a white background, maybe you can decide on a different color?
- also the "Back" and "Next" buttons are on white background so whatever color u decide for the icons we could maybe use the same one for those buttons as well?
- finally, if you change the orange on the landing then we need to inform tachyons to always use that orange (it's still set as the previous orange on the style.css file

2018-02-16 11:48 UTC, MarlenAw commented
@MynahMarie I'm still working on it! That's why I didn't assign you guys to review

2018-02-18 08:24 UTC, hoslack approved these changes

2018-02-18 10:12 UTC, MynahMarie requested changes
Great job for the styling! The only thing I would adjust before merging is to change the color of the text on the thank you page! After that I think it's good to go :)

2018-02-18 10:25 UTC, MynahMarie approved these changes

2018-02-18 10:37 UTC, Karyum commented
@MarlenAw can i review this right now ?

2018-02-18 10:46 UTC, Karyum requested changes
the css is using loads of `px` that's not responsive, it might be for your browsers but not really for other. and are you 100% sure you don't want to do it with tachyons? to keep it consistent and and responsive (since tachyons adds the webkits and stuff )

2018-02-18 10:46 UTC, Karyum commented on config/dev.js
> +  mongoURL: ''
what is  this doing here?

2018-02-18 11:03 UTC, MarlenAw commented
@Karyum I had to over write tachyons because it wasn't doing what I wanted

2018-02-18 13:20 UTC, Karyum approved these changes

2018-02-18 13:20 UTC, Karyum commented
# Amazing job

2018-02-18 13:20 UTC, merged